# charts/engram-cogitator/templates/ollama-service.yaml
{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "engram-cogitator.ollama.name" . }}
  labels:
    {{- include "engram-cogitator.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "engram-cogitator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}
