# charts/engram-cogitator/templates/postgres-secret.yaml
{{- if and (eq .Values.storage.driver "postgres") (not .Values.storage.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "engram-cogitator.fullname" . }}-postgres
  labels:
    {{- include "engram-cogitator.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.storage.postgres.password | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
